# Generated by Django 5.0.3 on 2024-04-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sections', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('accountType', models.CharField(choices=[('TA', 'Ta'), ('admin', 'Admin'), ('instructor', 'Instructor')], default='TA', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.course')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='TAs',
            field=models.ManyToManyField(blank=True, related_name='TAs', to='project_app.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.user'),
        ),
    ]
